# Font settings
font_family 'JetBrainsMono Nerd Font Mono'
font_size 12.0
italic_font auto
# Padding settings
window_padding_width  20
include themes/Monokai_Pro.conf
background_opacity 1.00
# Close confirmation settings
allow_remote_control yes
